FROM arm32v7/python:3.7
ENV PYTHONUNBUFFERED 1

COPY qemu-arm-static /usr/bin/

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /bot

COPY . /bot/
