version: '3'

volumes:
    mongo_volume:

services:
    mongo:
        image: mongo
        container_name: mongo
        env_file: .env
        ports:
            - "27017:27017"
        volumes:
            - mongo_volume:/data/db

    bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bot
        command: python -m bot.jack
        depends_on:
            - mongo
        volumes:
            - .:/bot
        env_file: .env

    session-watcher:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: session-watcher
        command: python -m watchers.session
        depends_on:
            - mongo
        volumes:
            - .:/bot
        env_file: .env

    ticket-watcher:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ticket-watcher
        command: python -m watchers.ticket
        depends_on:
            - mongo
        volumes:
            - .:/bot
        env_file: .env
